name: Deploy - dev

on:
  pull_request:
    branches: [main]
    types: [closed]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    needs: []
    uses: ./.github/workflows/_deploy-reusable.yml
    with:
      environment: dev
    secrets: inherit
